# Generated by Django 2.1.7 on 2019-03-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantloction',
            name='category',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
