# Generated by Django 2.1.7 on 2019-03-08 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20190308_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantloction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
